matrix:
  include:
    - language: go

      before_install:
        - go get github.com/mattn/goveralls

      before_script:
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1

      branches:
        only: master

      dist: bionic

      git:
        depth: 1

      go: 1.14.x

      notifications:
        email: false

      script:
        - cd $TRAVIS_BUILD_DIR/
        - golangci-lint run
        - $GOPATH/bin/goveralls -service=travis-ci
        - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/githubsearch main.go
        - CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -ldflags="-s -w" -o bin/githubsearch.exe main.go
